### PR TITLE
Fixed crash on api save, improved checking and error feedback

### LINKED ISSUE #2: App crashes when entering a custom API url
When entering a custom URL to the web app the website crashes and reloads. This is due to the way the popup is closed.

https://github.com/hcmlab/FaceMeshEditor/blob/2ca641771d0160c42ac37921edb2829921280d59/src/app.ts#L174

Tested in Google Chrome 125.0.6422.61
Safari 17.4.1 (18618.1.15.111.8, 18618)

### LINKED ISSUE #4: Add some kind of feedback if the user adds a custom api
Some feedback to the user would be benifical
- [x] The saving was successful
> the modal just disappears
- [x] The entered URI was viable
> the modal just closes
- [x] The API is reachable
> right now no checks are done

### PR DESCRIPTION
**Pull request by Marc-Lorenz**
Enables the user to save an api to use. 
Checks if the url is valid and reachable
serves information about the user

Bildschirmaufnahme 2024-05-23 um 12 40 45-3

Fixes #2
Fixes #4

### CODE REVIEW

File: src/app.ts [hunk 1]
```diff
@@ -170,14 +171,15 @@ export class App {
                     '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*'+ // port and path
                     '(\\?[;&a-z\\d%_.~+=-]*)?'+ // query string
                     '(\\#[-a-z\\d_]*)?$','i'); // fragment locator
-                // @ts-ignore
-                document.getElementById('modalSettingsModel').hide();
                 if (!!pattern.test(url)) {
                     this.models.custom.model = new WebServiceModel(url);
+                    console.log("Changed api to: ", this.getModel())
```
Comment (FHellmann) [inline src/app.ts]: Use a visible UI notification (e.g., https://getbootstrap.com/docs/5.3/components/toasts/)

File: src/app.ts [hunk 2]
```diff
@@ -170,14 +171,15 @@ export class App {
                     '(\\:\\d+)?(\\/[-a-z\\d%_.~+]*)*'+ // port and path
                     '(\\?[;&a-z\\d%_.~+=-]*)?'+ // query string
                     '(\\#[-a-z\\d_]*)?$','i'); // fragment locator
-                // @ts-ignore
-                document.getElementById('modalSettingsModel').hide();
                 if (!!pattern.test(url)) {
                     this.models.custom.model = new WebServiceModel(url);
+                    console.log("Changed api to: ", this.getModel())
                 } else {
+                    // Todo: add some kind of error message if the url is not viable
```
Comment (FHellmann) [inline src/app.ts]: Use a visible UI notification (e.g., https://getbootstrap.com/docs/5.3/components/toasts/)

File: index.html [hunk 3]
```diff
@@ -170,7 +170,10 @@ <h6>URL</h6>
                 <div class="modal-footer">
                     <button id="btnCancelModal" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel
                     </button>
-                    <button id="btnSaveCustomModel" type="submit" class="btn btn-primary">Save</button>
+                    <button id="btnSaveCustomModel" type="submit" class="btn btn-primary" data-bs-dismiss="modal">Save</button>
```
Comment (FHellmann) [inline index.html]: Wouldn't it be better to validate it first in typescript and close it there as well?

**Review by FHellmann — CHANGES_REQUESTED** [review]

**Review by FHellmann — APPROVED** [review]
